name: Run DecK
on: push
jobs:
  deck-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deck
        uses: kong/setup-deck@v1
        with:
          deck-version: '1.42.0'

      - name: Clone repository
        uses: actions/checkout@v2

      - name: Run DecK ping
        run: deck gateway ping --konnect-addr https://us.api.konghq.com --konnect-token kpat_C1m8GIbvammDDQIc69bgEHgAksgnXDL4N7uQALbaP84Q3Wv9M
