name: Run DecK
on: push
jobs:
  deck-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deck
        uses: kong/setup-deck@v1
        with:
          deck-version: '1.8.0'

      - name: Clone repository
        uses: actions/checkout@v2

      - name: Run DecK sync
        run: deck sync --kong-addr https://us.api.konghq.com --kong-workspace ../../konnect-export.yaml
